Repository leonardo-tx/Votify, pull requests merged in 2025-02, with the labels that each got.

#21 Remover pasta .idea
  .idea/.gitignore
  .idea/encodings.xml
  .idea/jpa-buddy.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
Labels: Configuração

#22 Adicionar dependências de teste
  pom.xml
Labels: Teste, Dependência

#24 back-end: Adicionar lógica de exceção
  votify-core/src/main/java/br/com/votify/core/utils/exceptions/VotifyErrorCode.java
  votify-core/src/main/java/br/com/votify/core/utils/exceptions/VotifyException.java
  votify-core/src/main/resources/messages.properties
Labels: API, Melhorias

#26 back-end: Adicionar dependência de criptografia ao core e configuração inicial de segurança
  votify-api/src/main/java/br/com/votify/api/configuration/SecurityConfig.java
  votify-core/pom.xml
Labels: API, Configuração, Dependência

#23 Draft: back-end: Adicionar a feature de cadastro de usuário
  votify-api/src/main/java/br/com/votify/api/controller/users/UserController.java
  votify-api/src/main/java/br/com/votify/api/dto/DTOInput.java
  votify-api/src/main/java/br/com/votify/api/dto/users/UserDTO.java
  votify-api/src/main/java/br/com/votify/api/dto/users/UserDetailedViewDTO.java
  votify-api/src/main/java/br/com/votify/api/dto/users/UserRegisterDTO.java
  votify-core/src/main/java/br/com/votify/core/domain/entities/users/AdminUser.java
  votify-core/src/main/java/br/com/votify/core/domain/entities/users/CommonUser.java
  votify-core/src/main/java/br/com/votify/core/domain/entities/users/ModeratorUser.java
  votify-core/src/main/java/br/com/votify/core/domain/entities/users/PermissionFlags.java
  votify-core/src/main/java/br/com/votify/core/domain/entities/users/User.java
  votify-core/src/main/java/br/com/votify/core/domain/entities/users/UserTypeEnum.java
  votify-core/src/main/java/br/com/votify/core/domain/entities/users/UserValidator.java
  votify-core/src/main/java/br/com/votify/core/repository/UserRepository.java
  votify-core/src/main/java/br/com/votify/core/service/UserService.java
  votify-core/src/main/java/br/com/votify/core/utils/CharacterUtils.java
  votify-core/src/main/java/br/com/votify/core/utils/exceptions/VotifyErrorCode.java
  votify-core/src/main/resources/messages.properties
Labels: Feature, Teste, API

#27 back-end: Adicionar módulo de teste
  pom.xml
  votify-core/pom.xml
  votify-test/pom.xml
  votify-test/src/test/resources/application.properties
Labels: Teste, Configuração, Dependência

#32 back-end: Adicionar testes relacionado a feature de cadastro
  votify-api/src/main/java/br/com/votify/api/controller/users/UserController.java
  votify-test/src/test/java/br/com/votify/api/controller/users/UserControllerTest.java
  votify-test/src/test/java/br/com/votify/core/domain/entities/users/UserValidatorTest.java
  votify-test/src/test/java/br/com/votify/core/service/UserServiceTest.java
  votify-test/src/test/java/br/com/votify/core/utils/CharacterUtilsTest.java
Labels: Teste, API
